version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tms_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tms_db
      MYSQL_USER: tms_user
      MYSQL_PASSWORD: tms_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Uncomment the following line if you want to initialize the database with SQL scripts
      # - ./init-scripts:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - tms_network

volumes:
  mysql_data:
    name: tms_mysql_data

networks:
  tms_network:
    name: tms_network 